{
 "title": "OpenTelemetry Collector HostMetrics (Node Exporter)",
 "description": "OpenTelemetry Collector otelcol-contrib hostmetrics (Node Exporter)",
 "tags": [
  "linux",
  "otelcol-contrib",
  "opentelemetry"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(system_cpu_time_seconds_total,job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(system_cpu_time_seconds_total{job=\"$job\"},job)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/documentation.md",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state!=\"idle\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/loadscraper/documentation.md",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_average_5m{job=\"${job}\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/loadscraper/documentation.md",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_average_15m{job=\"${job}\",}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/documentation.md",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization{ job=\"${job}\", system_cpu_state=\"free\" }"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/pagingscraper/documentation.md",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_usage{ job=\"${job}\", service_namespace=\"$service_namespace\", system_cpu_state=\"used\" }"
    }
   ]
  },
  {
   "title": "FS Used",
   "type": "gauge",
   "description": "Used FS\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#collecting-host-metrics-from-inside-a-container-linux-only",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_filesystem_utilization{job=\"${job}\",})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_logical_count{ job=\"${job}\", }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otelcol_process_uptime{job=\"${job}\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS Total",
   "type": "stat",
   "description": "Total FS\n\nhttps://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/filesystemscraper/documentation.md",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(system_filesystem_usage{job=\"${job}\", system_cpu_state=\"free\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit{job=\"${job}\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_paging_usage{job=\"${job}\",})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state=\"system\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state=\"user\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state=\"wait\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Busy Wait"
    },
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state=~\".*irq\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", state!~\".*irq\", system_cpu_state!=\"idle\", system_cpu_state!=\"user\", system_cpu_state!=\"wait\", system_cpu_state!=\"system\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(job) (irate(system_cpu_time_seconds_total{job=\"${job}\", system_cpu_state=\"idle\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(system_cpu_time_seconds_total{job=\"${job}\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_limit{job=\"${job}\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "system_memory_usage{job=\"${job}\", system_cpu_state=\"free\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(system_memory_usage{job=\"${job}\", system_cpu_state=~\"cached|buffered\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(system_paging_usage{job=\"$host\", system_cpu_state=\"used\"})",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_total{job=\"${job}\",network_io_direction=\"receive\"}[$__interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(system_network_io_total{job=\"${job}\",network_io_direction=\"transmit\"}[$__interval])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations{job=\"${job}\",network_io_direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(system_disk_operations{job=\"${job}\",network_io_direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(system_disk_io{job=\"${job}\",network_io_direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(system_disk_io{job=\"${job}\",network_io_direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_filesystem_utilization{job=\"${job}\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_utilization{ job=\"${job}\",}",
     "legendFormat": "{{process_command}} / {{state}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage{job=\"${job}\",}",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/documentation.md#processdiskoperations",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(process_disk_io{ job=\"${job}\", }[$__interval])",
     "legendFormat": "{{process_command}} / {{direction}}"
    }
   ]
  }
 ]
}