# Auth disabled for local storage
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

# OTEL Collector config
limits_config:
  allow_structured_metadata: true

memberlist:
# Refers to the configuration of many Loki instances

common:
# Something

schema_config:
# Something

storage_config:
  filesystem:
    directory: /tmp/loki/chunks